### ISSUE TITLE
Q: Precision, recall and F1 computed on clustered data only

### ISSUE THREAD

**Issue by andreas-wilm** [hudsondan/tcr-scapes#11]
Hi there, 

If I read the code correctly then it seems that precision, recall & F1 are only computed on clustered data. Was that the intention? Like this it is possibe to come up with a "perfect" method that however only clusters very few sequences conservatively. So instead of only showing F1 (from only clustered data) one would also always have to show the retention values as complement. Or do I misunderstand?

Many thanks

**Comment by andreas-wilm** [comment]
I see cases where a method clusters only 5 sequences out of 2500 and receives almost perfect precision, recall, f1score which doesn't make much sense, given that all input data has a label, i.e. there are plenty of FN here. An possible fix might be the following in `functions/metrics.py` (not tested):
```
ypred = pd.concat([ypred, pd.Series("", index=range(sum(df['cluster'].isnull())))]).reset_index(drop=True)
ytrue = pd.concat([ytrue, pd.Series(ytrue.iloc[0], index=range(sum(df['cluster'].isnull())))]).reset_index(drop=True)
```

**Comment by hudsondan** [comment]
Hi Andreas, thanks for your message. Yes, the metrics are computed on clustered data - data loss is captured with the retention score, so that one can identify artificially high scores attributable to low retention. Does that answer your question?

**Comment by andreas-wilm** [comment]
Hi Dan, thanks for taking the time to answer. And also thanks for making this much needed work available.

I realize that data loss is captured in retention.  That's why I argued that it's important to complement F1 with retention. Unfortunately the paper features retention only in the supplement.

I would argue that data loss should be directly reflected as FN, thereby influencing the recall (and F1) values dramatically. As it is, the recall and F1 metrics are very misleading. You can get super high recall (and F1) values if you only cluster a minute fraction of TCRs correctly. Consider the real example above where TCRdist3 clustered only 5 TCRs from 2500 TCRs for one epitope, but since those were correctly clustered you got really high recall and F1.

Anyway, I have a patch that treats uncalled TCRs as FN. Let me know if this is of interest to you

**Comment by hudsondan** [comment]
Thanks very much Andreas for your considered feedback -yes absolutely, happy to take a look into the suggested patch

**Comment by andreas-wilm** [comment]
Okay sure. Let me clean it up and build it in as optional. Afterwards I will create a PR

**Comment by hudsondan** [comment]
No problem, thanks Andreas - I have tested the implementation and your suggested code runs fine.

**Comment by andreas-wilm** [comment]
Hi Dan, please do not use the two lines I had shared earlier here. I deleted them from the post after I realized they actually don't do what they are supposed to do. I'll get back to you soon

**Comment by hudsondan** [comment]
Issue now resolved in latest commit - thank you Andreas!
